// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaLqB2HKia_0pTuiNqkge0Nx7zEFBmk28',
    appId: '1:640074479079:web:73e5643e925cc649b07942',
    messagingSenderId: '640074479079',
    projectId: 'alisveris-mobil',
    authDomain: 'alisveris-mobil.firebaseapp.com',
    storageBucket: 'alisveris-mobil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMwHtjxVvypADFbRWZMKoxj4mJOkj-iA',
    appId: '1:640074479079:android:966995ef59818dabb07942',
    messagingSenderId: '640074479079',
    projectId: 'alisveris-mobil',
    storageBucket: 'alisveris-mobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnwADZib2MSZ_I2i9rXLhY4X2IcXLMyOo',
    appId: '1:640074479079:ios:5c9cd16862c96fdeb07942',
    messagingSenderId: '640074479079',
    projectId: 'alisveris-mobil',
    storageBucket: 'alisveris-mobil.firebasestorage.app',
    iosBundleId: 'com.example.alisverisMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnwADZib2MSZ_I2i9rXLhY4X2IcXLMyOo',
    appId: '1:640074479079:ios:5c9cd16862c96fdeb07942',
    messagingSenderId: '640074479079',
    projectId: 'alisveris-mobil',
    storageBucket: 'alisveris-mobil.firebasestorage.app',
    iosBundleId: 'com.example.alisverisMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaLqB2HKia_0pTuiNqkge0Nx7zEFBmk28',
    appId: '1:640074479079:web:5c774425c6dddf39b07942',
    messagingSenderId: '640074479079',
    projectId: 'alisveris-mobil',
    authDomain: 'alisveris-mobil.firebaseapp.com',
    storageBucket: 'alisveris-mobil.firebasestorage.app',
  );
}
